"""initial schema

Revision ID: 76dcd7de8bd6
Revises: 
Create Date: 2026-04-03 12:44:58.293667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76dcd7de8bd6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('answer_hash', sa.String(length=64), nullable=True))
    op.create_index('idx_submissions_answer_hash', 'submissions', ['task_id', 'answer_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_submissions_answer_hash', table_name='submissions')
    op.drop_column('submissions', 'answer_hash')
    # ### end Alembic commands ###
